services:
  stress-test:
    image: polinux/stress
    command: "stress --timeout 100s --cpu 8"
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 100mb
  stress-test-2:
    image: polinux/stress
    command: "stress --timeout 100s --cpu 4"
    deploy:
      resources:
        limits:
          cpus: 3.0
          memory: 30mb
